name: collision_clones
author: Dzenan Ridjanovic <dzenanr@gmail.com>
version: 0.0.2
homepage: http://ondart.me/
description: A canvas game with moving cars of different sizes and colors, whose objective is to move the red car without collisions.
dependencies:
  browser: any
  json: any
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
